<?php

/**
 * @file
 * Admin functions (settings) for the hide_submit module.
 */

/**
 * Form builder. Configure hide submit settings.
 *
 * @ingroup forms
 * @see system_settings_form()
 */
function hide_submit_settings() {
  $config = config('hide_submit.settings');
  $form = array();
  $form['#config'] = 'hide_submit.settings';

  $form['hide_submit_basics_fs'] = array(
    '#type' => 'fieldset',
    '#title' => t('Basic settings'),
    '#collapsible' => TRUE,
    '#collapsed' => FALSE,
  );
  
  
  $form['hide_submit_basics_fs']['hide_submit_method'] = array(
    '#type' => 'select',
    '#options' => array(
      'disable' => t('Disable the submit buttons.'),
      'hide' => t('Hide the submit buttons.'),
      'indicator' => t('Built-in loading indicator.'),
    ),
    '#default_value' => $config->get('hide_submit_method'),
    '#title' => t('Blocking method'),
    '#description' => t('Choose the blocking method.'),
  );

  $form['hide_submit_basics_fs']['hide_submit_reset_time'] = array(
    '#type' => 'number',
    '#title' => t('Reset buttons after some time (ms).'),
    '#description' => t('Enter a value in milliseconds after which all buttons will be enabled. To disable this enter 0.'),
    '#default_value' => $config->get('hide_submit_reset_time'),    
    '#required' => TRUE,
  );


  $form['hide_submit_basics_fs']['hide_submit_exclude_paths'] = array(
    '#type' => 'textarea',
    '#title' => t('Exclude paths'),
    '#default_value' => $config->get('hide_submit_exclude_paths'),
    '#description' => t('Enter paths, one per line, where this module should not function. Wildcards are allowed. 
                          <br>Ex: admin/*
                          <br>It is recommended to exclude <strong>admin/*</strong>, as this module can interfere with some admin
                          forms.'),
  );
  
  
  
  
  $form['hide_submit_disable'] = array(
    '#type' => 'fieldset',
    '#title' => t('Disabling settings'),
    '#collapsible' => TRUE,
    '#collapsed' => FALSE,
  );

  $form['hide_submit_disable']['hide_submit_abtext'] = array(
    '#type' => 'textfield',
    '#title' => t('Append to buttons'),
    '#description' => t('This text will be appended to each of the submit buttons.'),
    '#default_value' => $config->get('hide_submit_abtext'),
  );

  $form['hide_submit_disable']['hide_submit_atext'] = array(
    '#type' => 'textarea',
    '#title' => t('Add next to buttons'),
    '#description' => t('This text will be added next to the submit buttons.'),
    '#default_value' => $config->get('hide_submit_atext'),
  );

  $form['hide_submit_hide'] = array(
    '#type' => 'fieldset',
    '#title' => t('Hiding settings'),
    '#collapsible' => TRUE,
    '#collapsed' => FALSE,
  );

  $form['hide_submit_hide']['hide_submit_hide_fx'] = array(
    '#type' => 'checkbox',
    '#title' => t('Use fade effects?'),
    '#default_value' => $config->get('hide_submit_hide_fx'),
    '#description' => t('Enabling a fade in / out effect.'),
  );

  $form['hide_submit_hide']['hide_submit_hide_text'] = array(
    '#type' => 'textfield',
    '#title' => t('Processing text'),
    '#default_value' => $config->get('hide_submit_hide_text'),
    '#description' => t('This text will be shown to the user instead of the submit buttons.'),
  );

  $form['hide_submit_indicator'] = array(
    '#type' => 'fieldset',
    '#title' => t('Indicator settings'),
    '#collapsible' => TRUE,
    '#collapsed' => FALSE,
    '#description' => t('Choose the spinner style as defined by the
      <a href="!library" target="_blank" rel="noopener">ladda.js jQuery library
      </a>. Examples of these styles can be found on the <a href="!examples"
      target="_blank" rel="noopener">Ladda example page</a>.', array(
      '!library' => '//github.com/hakimel/Ladda',
      '!examples' => '//lab.hakim.se/ladda/',
    )),
  );

  $form['hide_submit_indicator']['hide_submit_indicator_style'] = array(
    '#type' => 'select',
    '#options' => array(
      'expand-left' => t('expand-left'),
      'expand-right' => t('expand-right'),
      'expand-up' => t('expand-up'),
      'expand-down' => t('expand-down'),
      'contract' => t('contract'),
      'contract-overlay' => t('contract-overlay'),
      'zoom-in' => t('zoom-in'),
      'zoom-out' => t('zoom-out'),
      'slide-left' => t('slide-left'),
      'slide-right' => t('slide-right'),
      'slide-up' => t('slide-up'),
      'slide-down' => t('slide-down'),
    ),
    '#default_value' => $config->get('hide_submit_indicator_style'),
    '#title' => t('Built-In Loading Indicator Style'),
  );

  $form['hide_submit_indicator']['hide_submit_spinner_color'] = array(
    '#type' => 'select',
    '#options' => array(
      '#000' => t('Black'),
      '#A9A9A9' => t('Dark Grey'),
      '#808080' => t('Grey'),
      '#D3D3D3' => t('Light Grey'),
      '#fff' => t('White'),
    ),
    '#default_value' => $config->get('hide_submit_spinner_color'),
    '#title' => t('Built-In Loading Indicator Spinner Color'),
  );

  $form['hide_submit_indicator']['hide_submit_spinner_lines'] = array(
    '#type' => 'number',
    '#title' => t('The number of lines for the spinner'),
    '#default_value' => $config->get('hide_submit_spinner_lines'),    
  );

  return system_settings_form($form);
}


